### ISSUE TITLE
function.js returns wrong promise message

### ISSUE THREAD

**Issue by adeojoemmanuel** [adeojoemmanuel/free-port#1]
on running node test.js, it looks like it works fine, but its returning the wrong promise. need fix

**Comment by johnfoderaro** [comment]
Opened a PR for this: https://github.com/adeojoemmanuel/free-port/pull/2

**Comment by adeojoemmanuel** [comment]
thanks, your PR has been merged

**Comment by adeojoemmanuel** [comment]
@johnfoderaro the  file  returns both promises instead of one, you can check out the test.js to see how it works

**Comment by johnfoderaro** [comment]
Sure. I can take a look tonight. I believe the usage of promises should be revisited for this app.

**Comment by johnfoderaro** [comment]
@adeojoemmanuel I am having a little trouble following along with the repository, I think there are a few extraneous files at play here that may be making things tricker than the need to be. I added two new files: `update.js` and `update.test.js` in pul request #4 that may be of some help to you going forward, as it's my best take on what your desired behavior may be. Best of luck!!

**Comment by adeojoemmanuel** [comment]
thanks @johnfoderato would make use  of them
